### ISSUE TITLE
ApJ#1: Seeing figure 1 update

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#32]
From #31:

* It would be good to have more current seeing data in Figure 1. Seeing always seems to get worse after site selection probably due to regression to the mean.

**Comment by ivezic** [comment]
Chuck, do we have more current seeing data?

**Comment by cclaver** [comment]
We have had no seeing measurements from the LSST site since this figure was made.  Were are expected to resume DIMM seeing measurements late 2018/ early 2019.

We could obtain recent DIMM data from the nearby Gemini site as a proxy if we want something more recent than what is shown in the figure.  This of course would nat be the actual LSST site.

**Comment by ivezic** [comment]
> The "Deep-Wide-Fast" survey is supplemented by a "Very Deep" survey and a "Fast time domain" 
> survey [in the abstract]. This is too reminiscent of Starbucks' coffee sizes, where "grande" isn't big.

"Very" was meant to apply to both "Deep" and "Fast"; fixed.

**Comment by ivezic** [comment]
Wrong issue...

> It would be good to have more current seeing data in Figure 1. Seeing always seems to get worse
> after site selection probably due to regression to the mean.

The LSST Project is will install a permanent seeing monitor at the summit in 2019. Since
it will take at least a year to collect an adequate data set, existing Figure 1 cannot be significantly
improved at this time.
