### ISSUE TITLE
ApJ #1: Figure 18 logarithmic color bar

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#34]
The deep drilling fields in Figure 18 do not appear to be very much deeper than the main survey: 1.8x on the color bar. This figure might need a logarithmic color bar.

**Comment by ivezic** [comment]
It is indeed a bit surprising that DDFs have ~<2 times as many visits as the main survey. To reach the target of being a magnitude deeper, they should have about 6 times as many visits. Lynne, can you please see what's going on and improve this figure, if possible?

**Comment by rhiannonlynne** [comment]
The colorbar just hits limits -- it doesn't mean that 1.8 is the actual value for the number of visits in the DD fields. I can see how this is confusing since the color bar  isn't an arrow pointing off to the right at that edge. 
 
Here's what it would look like if I did not restrict the color range, but still used a linear scale:
![image](https://user-images.githubusercontent.com/1855711/48234424-67ab7e00-e36e-11e8-9539-66a2c2d5af90.png)

**Comment by rhiannonlynne** [comment]
And here's what the same plot looks like using a log scale: 

![image](https://user-images.githubusercontent.com/1855711/48234469-9164a500-e36e-11e8-862e-584416fca859.png)

**Comment by rhiannonlynne** [comment]
Or removing the normalization value: 

![image](https://user-images.githubusercontent.com/1855711/48234502-b9540880-e36e-11e8-83f0-8318c250fed2.png)

**Comment by rhiannonlynne** [comment]
But maybe this comes closer to the spirit intended? Color bar still constrained, but shows that the DD fields get > 100 times more visits.

![image](https://user-images.githubusercontent.com/1855711/48234610-1d76cc80-e36f-11e8-9bfd-bf0c8338cdd2.png)

**Comment by rhiannonlynne** [comment]
I don't entirely like the log options .. would this work?

![image](https://user-images.githubusercontent.com/1855711/48279351-3205a400-e405-11e8-9156-580044876207.png)

**Comment by rhiannonlynne** [comment]
I don't entirely like the options above -- would this be better? 

![image](https://user-images.githubusercontent.com/1855711/48279540-bbb57180-e405-11e8-9fb8-f1ba56819ad8.png)

**Comment by ivezic** [comment]
I like the last version! Could you please:
- replace the figure in the paper (and git push it or issue a PR)
- add to the caption the actual number of visits in DDFs (is it 500 or more?)
You may want to use more colors for the color bar (eg. red too), which would make
it easier to read off what is the typical number of visits for WFD, GP, NES and SP.

**Comment by rhiannonlynne** [comment]
You asked in email: what are the 'ghosty' bits along dec ~ -30? 
The answer is that these are places of higher overlap in the field tesselation. Even with dithering, these overlap locations remain, because the fields are just packed that way. With the feature based scheduler, however, those disappear because the orientation of the entire tesselation is randomized. 
I can't minimize the ghosty bits without making the entire plot look rather dull (low contrast between WFD and NES/SCP) after raising the max value to ~1000.

**Comment by rhiannonlynne** [comment]
DD fields receive between 2200 - 4200 visits in r band :
```sqlite> select count(*) from summaryallprops where proposalid=5 and filter='r' group by fieldid;
count(*)  
----------
2280      
4445      
4439      
4100      
2560 ```

and with a median of 200 visits in WFD fields.

**Comment by rhiannonlynne** [comment]
Done.
