### ISSUE TITLE
ApJ #1: Cadence figure needed

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#35]
A Figure showing the cadence for 1 or more typical spots would be useful, and it should show which filter is used for each visit. Something like a timeline with different color ticks indicating the visits. This should probably cover one lunation to keep the scale readable.

**Comment by ivezic** [comment]
Lynne, can you please cook up something here?

**Comment by rhiannonlynne** [comment]
Here's some starting points: 

I pulled out a year of observations from a WFD field (fieldid=1171) at RA=245.3, Dec=-34, (overhead)
and a field (id=315) at RA=263.0, Dec=-62 (south). 

This first version just stacks vertically (within each night) based on how many observations are in each night (so the spacing looks pretty orderly). 

![image](https://user-images.githubusercontent.com/1855711/48311379-d39b0b80-e553-11e8-83ef-238294e0d0fb.png)

![image](https://user-images.githubusercontent.com/1855711/48311382-da298300-e553-11e8-8b76-3125fd01ee7d.png)

**Comment by rhiannonlynne** [comment]
and this version is similar, but stacks within each night based on the actual time spacing in each night. So it adds information, but loses orderliness and maybe is too confusing (there is not a good separation between first/second observation, since later observations in each night are late enough that the gap needs to be too big). 

![image](https://user-images.githubusercontent.com/1855711/48311446-e6faa680-e554-11e8-818b-3d89641a52d5.png)

![image](https://user-images.githubusercontent.com/1855711/48311455-0560a200-e555-11e8-9127-6bb00b136cbd.png)

**Comment by ivezic** [comment]
Very pretty/informative! I like the version with orderly spacing much more. 
I propose to add another legend on the right (since you already have real
estate below or above existing legend): for each band, add the number of 
displayed observations, e.g 
u: 9
g: xx
r: xx
i: xx
z: xx
y: 24
for field 315 (Dec = -62). For a six-month period, one would on average
expect 3, 4, 9, 9, 8 and 8, so the chosen fields and season appear quite
well observed (e.g. field 1171 has over 30 z-band observations!). 
Another minor modification: in the title, please use both RA 
and Dec, and use the degree symbol (e.g. Dec = $-62^\circ$). 
Also, is there a good link to point people to if they want to get these data 
for the baseline cadence? 
Can you please add these figures to the paper and git push, or issue a PR?

**Comment by rhiannonlynne** [comment]
Still working on this one .. question though: where would be the preferred place to add this within the paper?

**Comment by ivezic** [comment]
I would add it as a short new paragraph between the last and penultimate paragraphs in Section 3.1.1.

**Comment by rhiannonlynne** [comment]
Added (see commit 72edd1430aeb6b792fdef90bfd3eb61abb2347d3). 
The figures were created in this notebook:
https://github.com/rhiannonlynne/notebooks/blob/master/Cadence%20plot.ipynb
