### ISSUE TITLE
ApJ #1: Trailing loss equation

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#39]
The trailing loss Eqn (8) has weird units. vt/theta should be dimensionless, so express v in arc-sec/sec, t in sec, and theta in arc-sec. This gets rid of the weird 24 in Eqn (9). Eqn (8) is basically noise \propto sqrt(FWHM^2+[trail length]^2) which is pessimistic relative to a search tuned for trails. This would have noise \propto sqrt(FWHM*sqrt(FWHM^2+[trail length]^2)) but would be a substantial computational burden to do a 4-D search for trails. You have to either explain your reasoning or give a citation for Eqn (8).

**Comment by ivezic** [comment]
Lynne, could you please take a detailed look at this comment?

**Comment by rhiannonlynne** [comment]
Pasting Zeljko's comment from a different issue (which I think was the wrong issue)

"Eq. 8 (now eq. 9) is based on a more detailed model, described in Section 5.1.4 in Jones et al. (2018)
that accounts for both SNR losses and detection losses due to non-optimal extraction profile.
We have added a reference to Jones et al. (2018). "

**Comment by timj** [comment]
Fixed in c4ad4a47
