### ISSUE TITLE
ApJ #1: Congressional mandate

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#43]
Also the Congressional mandate to find 90% of all NEOs 140 m and up will not be met, although finding a large fraction of NEOs brighter the H=22 is feasible. It's those pesky coal black C types that won't be found by LSST: a quarter of the NEOs at 140 m diameter have H > 23. The albedo used in \S 3.2.2 is hard to find, but the statement that H=22 is equivalent to 140 m gives 14%. Most C-types are much darker than this.

**Comment by ivezic** [comment]
Lynne, can you find appropriate place to add the albedo information (and perhaps address the comment about "pesky C types"...

**Comment by ivezic** [comment]
Eq. 8 (now eq. 9) is based on a more detailed model, described in Section 5.1.4 in Jones et al. (2018)
that accounts for both SNR losses and detection losses due to non-optimal extraction profile. 
We have added a reference to Jones et al. (2018).

**Comment by ivezic** [comment]
Previous comment was for a different issue. Here is the correct response for this issue:

It is customary to interpret 140 m size as H=22.  But we agree that there is a substantial fraction of 
asteroid with albedos below the implied median value of pV=0.142. We have added a reference to recent papers by Wright et al. (2016) and Grav et al. (2016) who discuss this issue in quantitative detail and find that a more realistic treatment of the albedo distribution can lead to a decrease in completeness on the order 5% (we note that "C types that won't be found" is too strong a statement 
because LSST completeness doesn't drop to 0 at H=22; indeed, it's still as high as 20% at H=25).
