### ISSUE TITLE
ApJ #1: Atmospheric dispersion in filters

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#44]
Specify the atmospheric dispersion in the filters. You mention that going for wider passbands would make this worse but do not give the magnitude. And call it "atmospheric dispersion", not "chromatic atmospheric refraction", even though these mean the same thing. Some instruments have ADC systems, none have CARC systems. This seems like an important systematic noise term for weak lensing studies.

**Comment by ivezic** [comment]
Andy, Robert, you are lucky winners of this comment. Please suggest our reply (Andy may want to consult with Ian Sullivan for numerical values).

**Comment by RobertLuptonTheGood** [comment]
How's this?

"The effect is largest in the blue and across wider passbands; in practice this means that the g band is the most strongly affected [numbers from Ian and Andy].  The term 'chromatic' is helpful as it reminds the reader that the atmospheric dispersion is a function of wavelength, and thus the magnitude of the effect is dependent on the colour of an object, but we are willing to call it 'atmospheric dispersion'.

The PSF is modelled as a function of the colour of the object, and given enough information about the object's morphology can be handled well enough to enable weak lensing measurements.  Recent papers which discuss this effect include Meyers and Burchat (
https://ui.adsabs.harvard.edu/link_gateway/2015ApJ...807..182M/doi:10.1088/0004-637X/807/2/182
) and Carlsten et al. (
https://ui.adsabs.harvard.edu/link_gateway/2018MNRAS.479.1491C/doi:10.1093/mnras/sty1636)"

**Comment by ivezic** [comment]
We have quantitatively specified atmospheric dispersion as a function of wavelength, and followed 
the suggestion to call it "atmospheric dispersion", instead of "chromatic atmospheric refraction"
Regarding the systematic noise for weak lensing studies, we have clarified that the PSF is modeled as 
a function of the color of the object, and given enough information about the object's morphology,
can be handled well enough to enable weak lensing measurements. We have also added references to
recent papers which discuss this effect (Meyers and Burchat 2015; Carlsten et al. 2018).
