### ISSUE TITLE
Referee response: Asteroid light curves

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#55]
The revisions are mainly just what I wanted. Figure 19 is quite nice.

I present the comments below just in case the authors don't want to
sound uninformed or the ApJ doesn't want to publish a paper that sounds
uninformed in one small aspect. But I want to emphasize that the paper
and the LSST it describes are both very valuable.

Comments about the asteroid lightcurve noise:
An RMS of 0.2 mag is not an amplitude of 0.3 mag in asteroid parlance,
since the amplitude is quoted from peak-to-valley. So this amplitude
is 0.56 mag which is quite substantial, and the calculation in the
reply to my first report is conservative. But the "correlated
errors between bands" are not what one gets from random phase light
curve errors. Still, color errors of 0.3/sqrt(100) are good, and
I like the idea of using 100's of widely spaced observations to
collect the data. I think a claim of color accuracy at least as
good as the SDSS is likely to be achieved, and the SDSS asteroid
colors have been very useful for classification.

But in terms of this manuscript, the requirement 
"The photometry should be better than 1-2% to measure asteroids'
colors and thus determine their types. The different filters
should be observed over a short time span to reduce apparent
variations in color due to changes in observing geometry,"
from page 7 is not being met by the proposed cadence, since the
asteroid's orientation is clearly a significant component of the
observing geometry. Thus the last sentence of the Figure 25 caption:
"LSST color measurements of asteroids will be more than twice as
accurate and will increase the number of objects by roughly two
orders of magnitude."
is not well justified, and will sound stupid to anybody who works
with asteroids. The authors need to make a better justification
of why they expect to do better than the SDSS even though the cadence
obviously does not meet the requirement. It seems to me that the
LSST has a Level 1 requirement to get data that can classify
asteroids, but the derived Level 2 requirement on page 7 is not
being met because it assumes a cadence they are not actually using.
But there is a work-around using the 100's of observations to beat
down the light curve noise. This needs to be described, and perhaps 
the requirement on page 7 rewritten in terms of data quality instead 
of cadence.

**Comment by ivezic** [comment]
I am glad to see that there is only one comment left, even if picky! @rhiannonlynne 
good job on Fig. 19!

Here is a proposed very simple way to address this comment (@timj I didn't know
what exactly was changed after my last commit, and my local repo acts weird, so 
I left these quick changes to you to implement): 

Page 7, the following text from the right column:

"The photometry should be better than 1–2% to measure asteroids’ colors and thus
 determine their types. The different filters should be observed over a short time 
span to reduce apparent variations in color due to changes in observing geometry, 
but should be repeated over many lunations in order to determine phase curves and 
allow shape modeling.” 

should be modified as:

"The photometric calibration should be better than 1–2% to measure asteroids’ colors 
and thus determine their types. If possible, the different filters should be observed 
over a short time span to reduce apparent variations in color due to changes in observing 
geometry, but should be repeated over many lunations in order to determine phase curves 
and allow shape modeling.” 

Figure 25 caption, the following text
"LSST color measurements of asteroids will be more than twice as accurate and will
increase the number of objects by roughly two orders of magnitude.”

should be modified as

"LSST color measurements of asteroids will be at least as accurate as SDSS measurements
shown here and will increase the number of objects by roughly two orders of magnitude.”

**Comment by timj** [comment]
Thanks. I'll take a look.

Your repo problem is likely caused by my rebasing the branch and fixing up the commit history. You'll have to delete your local branch and check it out again.

**Comment by timj** [comment]
Fixed in 2f95b78
